#!/usr/bin/env node
// Emits the high-resolution runner poses as SVG into sprites/runner_<pose>.svg (128 x 128, feet on y = 120,
// facing right; Look.lua mirrors for left). A pose is a handful of joints; limbs are thick round strokes drawn
// twice (outline, then fill) so the figure reads as inked line art over the 3D stage, not pixel art.
// Run: node tools/runner-rig.js   then   node bin/warehouse.js render preview_runner_strip --scale 4
import fs from 'node:fs';
import path from 'node:path';

const SIZE = 128;
const C = { ink: '#1b1b2f', body: '#5b5f73', far: '#474a5b', face: '#9aa0b8', white: '#f2f2f2', neon: '#7df9ff' };
const LIMB = 12, TORSO = 26, EDGE = 10; // fill widths and the outline added around them

// Joints per pose: [x, y]. Limbs are shoulder -> elbow -> hand and hip -> knee -> foot. "near" is the camera side.
// A running arm swung back has its elbow high and behind, hand low ("<" seen from the side), never the reverse.
const POSES = {
  idle: {
    head: [66, 28], neck: [64, 50], hip: [62, 80],
    nearArm: [[67, 53], [73, 70], [76, 88]], farArm: [[60, 53], [53, 70], [50, 88]],
    nearLeg: [[65, 80], [69, 98], [71, 113]], farLeg: [[59, 80], [55, 98], [53, 113]],
    scarf: 'M58 44 C 44 50, 46 66, 36 78', knot: [67, 48],
  },
  run_0: {
    head: [74, 26], neck: [68, 48], hip: [60, 78],
    nearArm: [[69, 51], [47, 47], [54, 62]], farArm: [[66, 51], [82, 64], [94, 52]],
    nearLeg: [[63, 78], [82, 93], [94, 112]], farLeg: [[58, 78], [40, 94], [28, 106]],
    scarf: 'M62 40 C 48 28, 42 50, 26 40 S 8 34, 6 42', knot: [72, 47],
  },
  run_1: {
    head: [74, 26], neck: [68, 48], hip: [60, 78],
    nearArm: [[69, 51], [84, 64], [96, 52]], farArm: [[66, 51], [45, 47], [50, 62]],
    nearLeg: [[63, 78], [44, 95], [30, 107]], farLeg: [[58, 78], [78, 93], [90, 112]],
    scarf: 'M62 40 C 50 44, 40 28, 26 42 S 8 48, 6 38', knot: [72, 47],
  },
};

const pts = (p) => p.map(([x, y]) => `${x},${y}`).join(' ');
function limb(points, fill, w = LIMB) {
  return `<polyline points="${pts(points)}" stroke="${C.ink}" stroke-width="${w + EDGE}"/>` +
    `<polyline points="${pts(points)}" stroke="${fill}" stroke-width="${w}"/>`;
}
function foot([x, y], fill) {
  // A shoe: a short stroke pointing forward, ink coloured like the pixel runner's boots.
  return `<line x1="${x - 3}" y1="${y}" x2="${x + 9}" y2="${y}" stroke="${C.ink}" stroke-width="${LIMB + 2}"/>` +
    `<line x1="${x - 1}" y1="${y - 1}" x2="${x + 7}" y2="${y - 1}" stroke="${fill}" stroke-width="4"/>`;
}
function hand([x, y]) {
  return `<circle cx="${x}" cy="${y}" r="7" fill="${C.ink}"/>`;
}

function svg(p) {
  const [hx, hy] = p.head;
  const r = 18;
  const parts = [
    // the scarf streams behind everything, with a soft neon glow under it
    `<path d="${p.scarf}" stroke="${C.neon}" stroke-width="18" opacity="0.28"/>`,
    `<path d="${p.scarf}" stroke="${C.ink}" stroke-width="13"/>`,
    `<path d="${p.scarf}" stroke="${C.neon}" stroke-width="7"/>`,
    // far side limbs, darker
    limb(p.farArm, C.far), hand(p.farArm[2]),
    limb(p.farLeg, C.far), foot(p.farLeg[2], C.far),
    // torso: one capsule from neck to hip, then the scarf knot on the collar under the chin
    limb([p.neck, p.hip], C.body, TORSO),
    `<circle cx="${p.knot[0]}" cy="${p.knot[1]}" r="6" fill="${C.neon}" stroke="${C.ink}" stroke-width="3"/>`,
    // near side limbs
    limb(p.nearLeg, C.body), foot(p.nearLeg[2], C.body),
    limb(p.nearArm, C.body), hand(p.nearArm[2]),
    // head: a light face in a dark hood, inked
    `<circle cx="${hx}" cy="${hy}" r="${r}" fill="${C.face}" stroke="${C.ink}" stroke-width="5"/>`,
    `<path d="M${hx + 2} ${hy - r} A ${r} ${r} 0 0 0 ${hx + 2} ${hy + r} Z" fill="${C.body}"/>`,
    // the visor: a neon band across the eyes, glowing
    `<rect x="${hx - 5}" y="${hy - 9}" width="${r + 8}" height="16" rx="8" fill="${C.neon}" opacity="0.3"/>`,
    `<rect x="${hx - 2}" y="${hy - 6}" width="${r + 2}" height="9" rx="4.5" fill="${C.neon}" stroke="${C.ink}" stroke-width="2.5"/>`,
    `<rect x="${hx + 6}" y="${hy - 4}" width="6" height="3" rx="1.5" fill="${C.white}"/>`,
  ];
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">\n` +
    `<!-- generated by tools/runner-rig.js; edit the pose there, not here -->\n` +
    `<g fill="none" stroke-linecap="round" stroke-linejoin="round">\n${parts.join('\n')}\n</g>\n</svg>\n`;
}

const outDir = path.resolve(process.cwd(), 'sprites');
for (const [pose, p] of Object.entries(POSES)) {
  const file = path.join(outDir, `runner_${pose}.svg`);
  fs.writeFileSync(file, svg(p));
  console.log('wrote', path.relative(process.cwd(), file));
}
